---
# tasks file for k8_Slave
- name: "installing docker"
  package:
     name: docker
     state: present
  ignore_errors: yes
- name: "Starting Docker"
  service:
     name: docker
     state:  restarted
  ignore_errors: yes
- name: "enabling docker"
  shell: "systemctl enable docker --now"
  changed_when: false

- name: Configure yum kubernetes repo
  yum_repository:
     name: "kubernetes"
     description: kubernetes repo
     baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
     enabled: yes
     gpgcheck: yes
     repo_gpgcheck: yes
     gpgkey:
       - "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
       - "https://packages.cloud.google.com/yum/doc/yum-key.gpg"
     exclude:
       - kublet
       - kubeadm
       - kubectl
- name: "Installing KubeAdm, kubectl and kubelet"
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    disable_excludes: "kubernetes"


- name: "Starting and Enabling  kubelet"
  service:
     name: kubelet
     state:  restarted
     enabled: yes
  ignore_errors: yes

- name: "Pulling Images using KubeAdm"
  shell: "kubeadm config  images pull"
  changed_when: false
  register: pull_images

- debug:
     var: pull_images.stdout_lines
- name: "Creating daemon.json file inside /etc/docker"
  shell: |
      cat <<EOF | sudo tee  /etc/docker/daemon.json
      {
      "exec-opts": ["native.cgroupdriver=systemd"]
      }
      EOF

  changed_when: false

- name: "Re-starting Docker"
  service:
     name: docker
     state:  restarted

- name: "Installing iproute-tc"
  package:
     name: iproute-tc

- name: "Setting bridge-nf-call-iptables to 1"
  shell: |
       echo "1"  > /proc/sys/net/bridge/bridge-nf-call-iptables
  changed_when: false

- name: "Joining Slaves to Master Node"
  shell: "{{ master_token  }}"
  ignore_errors: yes
  register: init

- debug:
    var: init.stdout_lines
