
---
# tasks file for k8_Master

- name: "installing docker"
  package:
     name: docker
     state: present
  ignore_errors: yes
- name: "Starting and Enabling  Docker"
  service:
     name: docker
     state:  restarted
     enabled: yes
  ignore_errors: yes

- name: Configure yum kubernetes repo
  yum_repository:
     name: "kubernetes"
     description: kubernetes repo
     baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
     enabled: yes
     gpgcheck: yes
     repo_gpgcheck: yes
     gpgkey:
       - "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
       - "https://packages.cloud.google.com/yum/doc/yum-key.gpg"
     exclude:
       - kublet
       - kubeadm
       - kubectl
- name: "Installing KubeAdm, kubectl and kubelet"
  yum:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    disable_excludes: "kubernetes"

- name: "Starting and Enabling  kubelet"
  service:
     name: kubelet
     state:  restarted
     enabled: yes
  ignore_errors: yes

- name: "Pulling Images using KubeAdm"
  shell: "kubeadm config  images pull"
  changed_when: false

- name: "Creating daemon.json file inside /etc/docker"
  shell: |
      cat <<EOF | sudo tee  /etc/docker/daemon.json
      {
      "exec-opts": ["native.cgroupdriver=systemd"]
      }
      EOF
  changed_when: false

- name: "Re-starting Docker"
  service:
     name: docker
     state:  restarted

- name: "Installing iproute-tc"
  package:
     name: iproute-tc

- name: "Setting bridge-nf-call-iptables to 1"
  shell: |
       echo "1"  > /proc/sys/net/bridge/bridge-nf-call-iptables
  changed_when: false

- name: "Initializing Master"
  shell: "kubeadm init --pod-network-cidr=10.244.0.0/16  --ignore-preflight-errors=NumCPU --ignore-preflight-errors=Mem"
  ignore_errors: yes
  register: init
- name: "Creating .kube directory"
  file:
       name: "$HOME/.kube"
       state: directory

- name: "Copy admin conf to user's .kube config"
  copy:
      src: /etc/kubernetes/admin.conf
      dest: $HOME/.kube/config
      remote_src: yes

- name: "changing owner permission"
  shell: "sudo chown $(id -u):$(id -g) $HOME/.kube/config"

- name: "Running Flannel Command"
  shell: "kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml"
  ignore_errors: yes

- name: "Generating Token"
  shell: "kubeadm token  create  --print-join-command"
  register: tokens
  ignore_errors: yes

- debug:
    var: tokens.stdout_lines
  register: tokens

